import Head from "next/head";
import { Inter } from "@next/font/google";
import HomePage from "../src/components/home/Home-page";

// const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps = async () => {
 const data = await import("../data/data");
 const { eventsCategories } = data;
 return {
  props: {
   data: eventsCategories,
  },
 };
};

const Home = ({ data }) => {
 return (
  <>
   <Head>
    <title>Events App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <HomePage data={data} />
  </>
 );
};

export default Home;
