import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { v4 as uuid } from "uuid";

// const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps = async () => {
 const { eventsCategories } = await import("/data/data.json");
 return {
  props: {
   data: eventsCategories,
  },
 };
};

const Home = ({ data }) => {
 return (
  <>
   <Head>
    <title>Events App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <header>
    <nav>
     <Link href="/" passHref legacyBehavior>
      <a>Home</a>
     </Link>
     <Link href="/events" passHref legacyBehavior>
      <a>Events</a>
     </Link>
     <Link href="/about-us" passHref legacyBehavior>
      <a>About Us</a>
     </Link>
    </nav>
   </header>
   <main className={styles.main}>
    {data.map((ev) => (
     <Link key={uuid()} href={`/events/${ev.id}`} passHref legacyBehavior>
      <a>
       <Image width={300} height={300} alt={ev.title} src={ev.image} />
       <h2>{ev.title}</h2>
       <p>{ev.description}</p>
      </a>
     </Link>
    ))}
   </main>
   <footer className={styles.footer}>
    <p>2022 Learning Next.js</p>
   </footer>
  </>
 );
};

export default Home;
